apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: pgops-reconfigure-config
  namespace: demo
spec:
  timeout: 20m
  type: Reconfigure
  databaseRef:
    name: ha-postgres
  configuration:   
    configSecret:
      name: pg-custom-config
