apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  name: "16.1-alpine-tds-fdw"
spec:
  archiver:
    addon:
      name: postgres-addon
      tasks:
        fullBackup:
          name: physical-backup
        fullBackupRestore:
          name: physical-backup-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
        volumeSnapshot:
          name: volume-snapshot
    walg:
      image: arnobkumarsaha/postgres-archiver:add-commit-time_16.1-alpine_linux_amd64
  coordinator:
    image: arnobkumarsaha/pg-coordinator:v0.33.0-1-g04b387c5_linux_amd64
  db:
    baseOS: alpine
    image: souravbiswassanto/postgres:16.1-alpine-tds-fdw
  distribution: Official
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
  initContainer:
    image: arnobkumarsaha/postgres-init:_linux_amd64
  podSecurityPolicies:
    databasePolicyName: postgres-db
  securityContext:
    runAsAnyNonRoot: false
    runAsUser: 70
  stash:
    addon:
      backupTask:
        name: postgres-backup-16.1
      restoreTask:
        name: postgres-restore-16.1
  ui:
    - name: pgadmin
      version: v2024.4.27
    - name: dbgate
      version: v2024.4.27
  updateConstraints:
    allowlist:
      - "16.4"
  version: "16.1"
